language: php
php:
  - '7.1'

matrix:
  include:
    - php: '7.1'
      env: PCRE=8.30

before_install:
  - if [ "$PCRE" != "" ]; then sh install-pcre.sh; fi
  - if [ "$PCRE" != "" ]; then PHP_BUILD_CONFIGURE_OPTS="--with-pcre-regex={$PWD}/pcre/pcre-{$PCRE}" php-build -i development 7.1.7 $HOME/.phpenv/versions/7.1.7; fi
  - if [ "$PCRE" != "" ]; then phpenv rehash; fi
  - if [ "$PCRE" != "" ]; then phpenv global 7.1.7; fi

before_script:
  - php -i | grep -i '^pcre'
  - composer install

script: php test.php
