language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

before_script:
  - phpenv config-rm xdebug.ini
  - php -i | grep -i '^pcre'
  - composer install

script: php test.php
